### ISSUE TITLE
Boa Noite.

### ISSUE THREAD

**Issue by alissonandrade2020** [jefersonseverino/cars-python#1]
Que tipo de programa é esse ???  :mask:  :vulcan_salute:

**Comment by jefersonseverino** [comment]
Boa tarde, é um exercício que fiz esses dias e publiquei aqui no GitHub. O programa consiste em você 
poder fazer várias operações com carros, como criar e excluir. Além disso, permite fazer alterações nas 
características da classe carro, como ligar ele, atribuir potência e algumas outras ações. Tudo isso feito
usando orientação a objeto e escrito em Python

Espero ter ajudado
